name: dog_breeds_app
description: Aplicativo Flutter para consultar razas de perros usando TheDogAPI
publish_to: "none" # No publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Gestión de estado
  provider: ^6.1.2

  # HTTP requests
  http: ^1.2.2

  # Google Fonts
  google_fonts: ^6.2.1

  # Obtener versión del app (para splash)
  package_info_plus: ^8.1.1

  # Íconos
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/paw_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/paw_icon.png"
  min_sdk_android: 21 # Asegúrate de que coincida con tu minSdkVersion en android/app/build.gradle
  remove_alph-ios: true
  adaptive_icon_background: "#B2FFFF"
  adaptive_icon_foreground: "assets/icon/paw_icon.png"